server:
  port: 8080

spring:
  datasource:
    username: oceanleo
    password: 99493lhy
    url: jdbc:mysql://localhost:3306/ssm?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

logging:
  level:
    com:
      oceanleo:
        blog:
          mapper: debug
